### ISSUE TITLE
win

### ISSUE THREAD

**Issue by spacex-3** [hanfangyuan4396/ntwork-bin-backup#1]
ERROR: Wheel 'ntwork' located at C:\Users\**\FileStorage\File\2024-08\ntwork-0.1.3-cp310-cp310-win_amd64.whl is invalid.

win11安装失败

**Comment by spacex-3** [comment]
C:\Users\**\dify-on-wechat>python --version
Python 3.10.10

C:\Users\**\dify-on-wechat>python -c "import platform; print(platform.architecture())"
('64bit', 'WindowsPE')

<img width="443" alt="image" src="https://github.com/user-attachments/assets/51e8b184-884a-41d3-ad0a-5521050c66fc">

**Comment by spacex-3** [comment]
没下载对源文件，直接右键另存为是有问题的><

**Comment by hanfangyuan4396** [comment]
请问win11上是可用的吗

**Comment by spacex-3** [comment]
> 请问win11上是可用的吗

可以用的，谢谢
